#!/usr/bin/env python3
"""Plot entry point for L01028 storage outputs.

Figures are generated by `run_L01028_storage_volume.py`; this script verifies
that the expected figure package exists for reproducible command histories.
"""

from __future__ import annotations

import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
FIG_DIR = ROOT / "outputs/reference_frames/L01028_500m_fixed_quality_median_v1/bounded_model_redevelopment/groundwater_storage_volume/attempt_storage_v1_001/figures"


def main() -> int:
    figures = sorted(p.name for p in FIG_DIR.iterdir() if p.is_file()) if FIG_DIR.exists() else []
    payload = {"figures_status": "passed" if len(figures) >= 8 else "missing", "figures": figures}
    print(json.dumps(payload, indent=2, sort_keys=True))
    return 0 if payload["figures_status"] == "passed" else 1


if __name__ == "__main__":
    raise SystemExit(main())
